### PR TITLE
fix uint testing data overflow bug

### LINKED ISSUE #1998: Tests fail on 32-bit due to untyped integer overflows
### Describe the bug

Tests fail to build on 32-bit due to the assumption that untyped integers are 64-bit.

### Expected Behavior

Tests build successfully and pass.

### Current Behavior

In main module:
```
# github.com/aws/aws-sdk-go-v2/aws/retry [github.com/aws/aws-sdk-go-v2/aws/retry.test]
aws/retry/jitter_backoff_test.go:41:16: cannot use 1 << 53 (untyped int constant 9007199254740992) as int value in struct literal (overflows)
```
And in service/internal/benchmark module:
```
# github.com/aws/aws-sdk-go-v2/service/internal/benchmark/dynamodb [github.com/aws/aws-sdk-go-v2/service/internal/benchmark/dynamodb.test]
dynamodb/customizations_test.go:41:22: cannot use 4158286593 (untyped int constant) as int value in struct literal (overflows)
dynamodb/customizations_test.go:42:22: cannot use 3095499784 (untyped int constant) as int value in struct literal (overflows)
```

### Reproduction Steps

Run tests for 386 arch:
```
GOARCH=386 go test ./...
```

### Possible Solution

For the main module, `ExponentialJitterBackoff.BackoffDelay` takes an unsigned int for the attempt. To avoid breaking an existing API, the test should either use a literal constant which won't overflow on 32-bit, or use platform-specific constants, e.g. `Math.MaxInt`

For the service/internal/benchmark module, the relevant `testData` struct members can simply be changed to int64, e.g.
```diff
 type testData struct {
    filename         string
-   respChecksum     int
-   respGzipChecksum int
+   respChecksum     int64
+   respGzipChecksum int64
 }
```
The use of `strconv.Itoa` in the test would also need to be changed to `strconv.FormatInt`, since the former takes an untyped int. However, this does beg the question of why larger-than-32-bit test values are being used in the `X-Amz-Crc32` header. Is it not a _32-bit_ checksum?

### Additional Information/Context

_No response_

### AWS Go SDK V2 Module Versions Used

```
github.com/aws/aws-sdk-go-v2 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/smithy-go@v1.13.5 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.13.5 github.com/jmespath/go-jmespath@v0.4.0
github.com/jmespath/go-jmespath@v0.4.0 github.com/jmespath/go-jmespath/internal/testify@v1.5.1
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/davecgh/go-spew@v1.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/pmezard/go-difflib@v1.0.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/stretchr/objx@v0.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 gopkg.in/yaml.v2@v2.2.8
gopkg.in/yaml.v2@v2.2.8 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
```

### Compiler and Version used

go version go1.19.5 linux/amd64

### Operating System and version

Debian sid

### PR DESCRIPTION
**Pull request by wty-Bryant**
fix #1998 int overflow on 32bit architectures

### CODE REVIEW

File: aws/retry/jitter_backoff_test.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func TestExponentialJitterBackoff_AttemptDelay(t *testing.T) {
 		"max delay": {
 			MaxBackoff: 20 * time.Second,
 			RandFloat:  func() (float64, error) { return maxB, nil },
-			Attempt:    1 << 53,
+			Attempt:    math.MaxInt,
```
Comment (aajtodd) [inline aws/retry/jitter_backoff_test.go:41]: **fix**:

`math.MaxInt` was only [added](https://go.dev/doc/go1.17) in Go 1.17. Probably just change this to `int64` type explicitly or change the value to be within range

**Review by aajtodd — CHANGES_REQUESTED** [review]
There are failing tests that need addressed, see my comment
