### PR TITLE
breakfix: convert public access block config fields to nilable like s3

### LINKED ISSUE #2384: s3control `types.PublicAccessBlockConfiguration` failing to serialize correctly when all (boolean) fields are `false`
### Describe the bug

The s3control service's `types.PublicAccessBlockConfiguration` structure fails to serialize correctly when all its (boolean) fields are `false`:

```go
input := &s3control.PutPublicAccessBlockInput{
	AccountId: aws.String("123456789012"),
	PublicAccessBlockConfiguration: &types.PublicAccessBlockConfiguration{
		BlockPublicAcls:       false,
		BlockPublicPolicy:     false,
		IgnorePublicAcls:      false,
		RestrictPublicBuckets: false,
	},
}
```

HTTP request and response:

```
  http.request.body=
  | <PublicAccessBlockConfiguration xmlns="http://awss3control.amazonaws.com/doc/2018-08-20/"></PublicAccessBlockConfiguration>
  http.response.body=
  | <?xml version="1.0" encoding="UTF-8"?>
  | <ErrorResponse><Error><Code>InvalidRequest</Code><Message>Must specify at least one configuration.</Message></Error><RequestId>7ESN3M87GKFSGK0T</RequestId><HostId>XoGVKFltZ6t++IFu6TDSibAhtgLGAPC9xSUa/kv+UEm6lxmQNeurd3TWYgVPGaFj5pzjiXoIv/g=</HostId></ErrorResponse>
```

### Expected Behavior

Expected no error (AWS SDK for Go v1 behavior).

### Current Behavior

See above.

### Reproduction Steps

See above.

### Possible Solution

_No response_

### Additional Information/Context

Relates https://github.com/aws/aws-sdk-go-v2/issues/2162.

### AWS Go SDK V2 Module Versions Used

```console
% grep s3control go.mod
	github.com/aws/aws-sdk-go-v2/service/s3control v1.37.1
```

### Compiler and Version used

go version go1.20.10 darwin/amd64

### Operating System and version

macOS Ventura 13.6

### PR DESCRIPTION
**Pull request by lucix-aws**
Manually patch s3control `PublicAccessBlockConfiguration` fields to pointer types in advance of it being fixed in the model, this was missed in the previous s3control breakfix push.

Closes #2384.

### CODE REVIEW

File: codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/customization/RemoveDefaults.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        return ModelTransformer.create().mapShapes(model, it ->
+                fromShapes.contains(it.getId())
+                        ? withoutDefault(it)
+                        : it
+        );
+    }
+
+    private Shape withoutDefault(Shape shape) {
+        var builder = ((ToSmithyBuilder<?>) shape).toBuilder();
+        return ((AbstractShapeBuilder<?, ?>) builder).removeTrait(DefaultTrait.ID).build();
```
Comment (milesziemer) [inline codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/customization/RemoveDefaults.java:50]:
```suggestion
        return Shape.shapeToBuilder(shape).removeTrait(DefaultTrait.ID).build();
```
Weird casting stuff was only needed in kotlin

**Review by milesziemer — APPROVED** [review]

**Review by wty-Bryant — APPROVED** [review]

**Review by isaiahvita — APPROVED** [review]
