### PR TITLE
Fix XML unmarshaler not correctly unmarshaling list of timestamp values

### LINKED ISSUE #1892: GetBucketLocation fail if s3 bucket is locate in us-east-1
### Describe the bug

We use aws-sdk-go-v2 to list all buckets and then we will do so put action for some buckets.
There is  a bucket locate on us-east-1, and we found when we perform `s3.GetBucketLocation` for this bucket, if fail.
and if we use aws cli to list this bucket region, it success.
the reason we found is file `service/s3/types/enums.go` it does not support `us-east-1` region.

### Expected Behavior

we can perform `s3.GetBucketLocation` successfully and get bucket region back if bucket locate on us-east-1.

### Current Behavior

if bucket locate on us-east-1, perform `s3.GetBucketLocation` can not get the bucket region.

### Reproduction Steps

create bucket on `us-east-1`, then perform `s3.GetBucketLocation(ctx, &s3.GetBucketLocationInput{Bucket: aws.String(name)})`

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS Go SDK V2 Module Versions Used

v1.16.16

### Compiler and Version used

1.18.3

### Operating System and version

RedHat 8.5

### PR DESCRIPTION
**Pull request by jasdel**
Fixes a bug in the XML unmarshaler that would incorrectly try to
unmarshal "time.Time" parameters that did not have the struct tag type
on them. This would occur for nested lists like CloudWatch's
GetMetricDataResponse MetricDataResults timestamp parameters.

Adds protocol tests for XML unmarshaling with list of timestamps.

Related to aws/aws-sdk-go#1894

Fix #1892

### CODE REVIEW

File: private/protocol/xml/xmlutil/unmarshal.go [hunk 1]
```diff
@@ -52,14 +54,26 @@ func parse(r reflect.Value, node *XMLNode, tag reflect.StructTag) error {
 	if t == "" {
 		switch rtype.Kind() {
 		case reflect.Struct:
-			t = "structure"
+			// also it can't be a time object
+			_, tok := r.Interface().(*time.Time)
```
Comment (xibz) [inline private/protocol/xml/xmlutil/unmarshal.go]: May be cleaner to do something like this
```go
if _, ok := reflect.Indirect(v).Interface().(time.Time); ok {
}
```

Comment (jasdel) [reply private/protocol/xml/xmlutil/unmarshal.go]: Wouldn't be able to use `Indirect` because that would produce a nil value for fields, which `Interface` will panic on.

**Comment by jasdel** [comment]
Merge pending until we're able to regression test this with the other REST XML protocol services.

**Comment by opavader** [comment]
Can this be expedited ?
Seems like major bug to me.

File: models/protocol_tests/output/rest-xml.json [hunk 2]
```diff
@@ -42,6 +42,15 @@
...
             "shape": "TimestampType"
+          },
+          "Blobs": {
+            "shape": "Blobs"
+          },
+          "Timestamps": {
+            "shape": "Timestamps"
+          },
+          "Float64s": {
+            "shape": "Float64s"
```
Comment (xibz) [inline models/protocol_tests/output/rest-xml.json]: Can we add `JSONValue` to this test?
