### PR TITLE
aws: Fix Pagination handling of empty string NextToken

### LINKED ISSUE #84: Inconsistent pagination
### Version of AWS SDK for Go?

What's the command to determine this?
Else, going to assume https://github.com/aws/aws-sdk-go-v2/commit/493e3ced184b77eff33393092e91fd3e1d0dbfd8

### Version of Go (`go version`)?

go version go1.9.2 linux/amd64

### What issue did you see?

With medialive the way to test an empty token is `*next == ""`. on mediapackage it's `next == nil`. I'm puzzled why.

* https://godoc.org/github.com/aws/aws-sdk-go-v2/service/medialive#ListChannelsOutput
* https://godoc.org/github.com/aws/aws-sdk-go-v2/service/mediapackage#ListOriginEndpointsOutput

### Steps to reproduce

Compare

* https://s.natalian.org/2018-01-09/live.go
* https://s.natalian.org/2018-01-09/pkgs.go

Notice if live.go uses:

        if next == nil {
            break
        }

It just goes in an infinite loop.

### PR DESCRIPTION
**Pull request by jasdel**
Fixes the SDK's handling of a Pagination NextToken's value being an
empty string compared to a nil value. The SDK was expecting NextToken's
to always be unset (nil) and treating any non-nil value as a valid
value. This was not the case in MediaLive's List APIs. As those APIs
return a empty string value instead of null or not setting the field at
all.

This issue exists in both the v1 and v2 SDKs.

Fix #84

### CODE REVIEW

File: aws/request_pagination_test.go [hunk 1]
```diff
@@ -586,6 +586,82 @@ func TestPagination_Standalone(t *testing.T) {
...
+		Value     *string
+		NextToken *string
+	}
+
+	expect := []struct {
+		Value, PrevToken, NextToken *string
+	}{
+		{aws.String("FirstValue"), aws.String("InitalToken"), aws.String("FirstToken")},
+		{aws.String("SecondValue"), aws.String("FirstToken"), aws.String("SecondToken")},
+		{aws.String("ThirdValue"), aws.String("SecondToken"), nil},
```
Comment (xibz) [inline aws/request_pagination_test.go]: Do we not have a test to test for `""`?

File: aws/request_pagination.go [hunk 2]
```diff
@@ -141,13 +141,29 @@ func (r *Request) nextPageTokens() []interface{} {
...
+				continue
+			}
+		case string:
+			if len(tv) == 0 {
+				tokens = append(tokens, nil)
+				continue
+			}
 		}
+
+		tokenAdded = true
```
Comment (xibz) [inline aws/request_pagination.go]: if they are bunch of empy strings, wouldn't `tokenAdded` not be set to `true`? Meaning this would never return the `tokens`

Comment (jasdel) [reply aws/request_pagination.go]: `tokenAdded` is present if a valid token is added. The `tokens` slice is a sparse array. Its index directly correspond to indexes in another slice.

If all of the values at the `outTokens` paths are empty strings there will be no valid tokens in the `tokens` slice. In that case returning `nil` would be the correct action.  If there is at least one valid value in `outTokens` paths the `tokenAdded` will be set to true.

File: aws/request_pagination_test.go (hunk 1 above)
Comment (jasdel) [reply aws/request_pagination_test.go]: Yeah, [TestPagination_Standalone](https://github.com/aws/aws-sdk-go-v2/pull/94/files#diff-c0f28140336767027cefe425e291979cR528) is that testcase. The SDK already had this testcase but the way it [worked](https://github.com/aws/aws-sdk-go-v2/pull/94/files#diff-c0f28140336767027cefe425e291979cR561) prevented the bug from manifesting.
