### PR TITLE
codegen: Updates SDK's generated serde for unmodeled operation input/output

### LINKED ISSUE #1047: sqs.Client.TagQueue returns an error but still succeessfully tags a resource
Confirm by changing [ ] to [x] below to ensure that it's a bug:

- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

Attempts to tag an SQS queue with [sqs.Client.TagQueue](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sqs@v0.31.0?#Client.TagQueue) call fails with the following error:

	operation error SQS: TagQueue, https response error StatusCode: 200, RequestID: 551b5c11-ecbd-55de-8d46-046a7bfc9c2d, deserialization failed, failed to decode response body, TagQueueResult node not found

API call actually succeeds, as provided tags appear on a resource.

**Version of AWS SDK for Go?**

0.31.0

**Version of Go (`go version`)?**

go version go1.16beta1 darwin/arm64

**To Reproduce (observed behavior)**

Steps to reproduce the behavior (please share code or minimal repo)

go.mod contents:

```
module sdk-bug

go 1.16

require (
	github.com/aws/aws-sdk-go-v2 v0.31.0
	github.com/aws/aws-sdk-go-v2/config v0.4.0
	github.com/aws/aws-sdk-go-v2/service/sqs v0.31.0
)
```

main.go contents:

```go
package main

import (
	"context"
	"errors"
	"flag"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
)

func main() {
	log.SetFlags(0)
	flag.Parse()
	if err := run(context.Background(), flag.Arg(0)); err != nil {
		log.Fatal(err)
	}
}

func run(ctx context.Context, queueURL string) error {
	if queueURL == "" {
		return errors.New("provide a queue url to tag")
	}
	log.Println("SDK version:", aws.SDKVersion)
	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		return err
	}
	svc := sqs.NewFromConfig(cfg)
	_, err = svc.TagQueue(ctx, &sqs.TagQueueInput{
		QueueUrl: &queueURL,
		Tags:     map[string]string{"Environment": "staging"},
	})
	return err
}
```

Build and run this program providing an SQS queue URL as a first positional argument.

**Expected behavior**

Program prints SDK version on stderr and finishes with 0 exit status. Resource is tagged.

**Actual behavior**

Program prints SDK version on stderr and finishes with non-zero exit status, printing an error:

    operation error SQS: TagQueue, https response error StatusCode: 200, RequestID: 551b5c11-ecbd-55de-8d46-046a7bfc9c2d, deserialization failed, failed to decode response body, TagQueueResult node not found

Resource *is* tagged.

**Additional context**

Similar error happens with [rds.Client.AddTagsToResource](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds@v0.31.0#Client.AddTagsToResource) calls.

### PR DESCRIPTION
**Pull request by jasdel**
Updates the SDK's generate serializers and deserializers for operations without modeled input and output types. This fixes #1047 where the SDK was attempting to deserialize a response from a service for an operation that had no modeled output. The SDK should of ignored the response instead of trying to deserialize it.

This update will not attempt to serialize inputs for operations without modeled inputs, and will discard responses from services of operations with unmodeled outputs.

Related to aws/smithy-go#261
Fixes #1047

### CODE REVIEW

File: codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/XmlProtocolUtils.java [hunk 1]
```diff
@@ -237,7 +237,9 @@ private static String getSerializedXMLShapeName(ProtocolGenerator.GenerationCont
         Optional<SyntheticClone> clone = shape.getTrait(SyntheticClone.class);
         if (clone.isPresent()) {
             SyntheticClone cl = clone.get();
-            shapeName = cl.getArchetype().getName();
+            if (cl.getArchetype().isPresent()) {
+                shapeName = cl.getArchetype().get().getName();
+            }
```
Comment (skotambkar) [inline codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/XmlProtocolUtils.java:242]: I thought the only purpose of clone was to stub a top-level shape if not present in model. 

This code-block suggests we rename shapes using synthetic shape, even when they are present in the model. Is that true?

**Review by skotambkar — APPROVED** [review]

**Review by skmcgrail — APPROVED** [review]
