### PR TITLE
switch to code-generated waiters for remaining services

### LINKED ISSUE #2977: finish rollout of codegen-based waiters
We recently introduced code-generated waiter support. We've since rolled out the feature in the EC2 service and have not received any reports of regressions from customers.

We should complete the rollout of generated waiters, as this will allow us to drop our dependency on `go-jmespath`.

### PR DESCRIPTION
**Pull request by lucix-aws**
Closes #2977

### CODE REVIEW

**Review by wty-Bryant — APPROVED** [review]

File: service/acm/api_op_DescribeCertificate.go [hunk 1]
```diff
@@ -326,29 +325,23 @@ func (w *CertificateValidatedWaiter) WaitForOutput(ctx context.Context, params *
...
-				return false, fmt.Errorf("waiter comparator expected types.DomainStatus value, got %T", pathValue)
-			}
-
-			if string(value) != expectedValue {
+		expectedValue := "SUCCESS"
+		match := len(v4) > 0
+		for _, v := range v4 {
+			if string(v) != expectedValue {
 				match = false
+				break
```
Comment (Madrigal) [inline service/acm/api_op_DescribeCertificate.go:344]: nice extra optimization we got

File: service/ses/api_op_GetIdentityVerificationAttributes.go [hunk 2]
```diff
@@ -341,29 +340,18 @@ func (w *IdentityExistsWaiter) WaitForOutput(ctx context.Context, params *GetIde
 func identityExistsStateRetryable(ctx context.Context, input *GetIdentityVerificationAttributesInput, output *GetIdentityVerificationAttributesOutput, err error) (bool, error) {
 
 	if err == nil {
-		pathValue, err := jmespath.Search("VerificationAttributes.*.VerificationStatus", output)
-		if err != nil {
-			return false, fmt.Errorf("error evaluating waiter state: %w", err)
+		v1 := output.VerificationAttributes
```
Comment (Madrigal) [inline service/ses/api_op_GetIdentityVerificationAttributes.go:343]: [observation] This wildcard took a 2nd reading. The model is 

```
VerificationAttributes map[string]types.IdentityVerificationAttributes
```

So iterating through the values gets us the same result as the wildcard

File: service/ecs/api_op_DescribeServices.go [hunk 3]
```diff
@@ -541,94 +538,100 @@ func (w *ServicesStableWaiter) WaitForOutput(ctx context.Context, params *Descri
...
-			if string(*value) == expectedValue {
-				return false, fmt.Errorf("waiter state transitioned to Failure")
-			}
+		if match {
+			return false, fmt.Errorf("waiter state transitioned to Failure")
 		}
 	}
 
 	if err == nil {
-		pathValue, err := jmespath.Search("length(services[?!(length(deployments) == `1` && runningCount == desiredCount)]) == `0`", output)
```
Comment (Madrigal) [inline service/ecs/api_op_DescribeServices.go:616]: For my sanity reading this expression, this is what this means (which may be easier to reason in the newer version)

* is there an ongoing deployment -> `length(deployments) == 1`
* do we have enough containers running already -> `runningCount == desiredCount`
* are there any services where this is not happening -> `[?!(a&&b)]`
* on this cluster, is the service stable, meaning there are no deployments and there are enough containers running? -> `length[] == 0`

**Review by Madrigal — APPROVED** [review]
We have about 600 waiters that changed with this new re-gen, so it's impossible to review them all. I did a quick search for `jmespath.Search` and manually classified them into the following 6 types of waiters

# Simple selector
* `jmespath.Search("AuditReportStatus", output)`
* Sample location service/acmpca/api_op_DescribeCertificateAuthorityAuditReport.go

# Nested selector with list
* `jmespath.Search("Certificate.DomainValidationOptions[].ValidationStatus", output)`
* Sample location service/acm/api_op_DescribeCertificate.go

# Wildcard selector (only one I saw)
* `jmespath.Search("VerificationAttributes.*.VerificationStatus", output)`
* Sample location service/ses/api_op_GetIdentityVerificationAttributes.go

# Length selector
* `jmespath.Search("length(DBClusterSnapshots) == `0`", output)`
* Sample location service/rds/api_op_DescribeDBClusterSnapshots.go

# Complex filter expression
* `jmespath.Search("length(services[?!(length(deployments) == `1` && runningCount == desiredCount)]) == `0`", output)`
* Location service/ecs/api_op_DescribeServices.go

# AND simple selector
* `jmespath.Search("status != 'CANCELLING' && status != 'CANCELLED'", output)`
* Sample location service/neptunegraph/api_op_GetExportTask.go

Took a look at the generated code and ensured that the code is equivalent and correct. Left some comments for observations, but everything looks correct. 

This is a great change to get rid of one of our last dependencies in the Go SDK 🎉
