### PR TITLE
 aws/signer/v4: Fix presign hoisting for x-amz-tagging header

### LINKED ISSUE #1016: service/s3: presigned PutObject with Tagging set does not add tagging to object in S3 bucket.
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
Objects uploaded to S3  ith presign Put Object URL with`Tagging` parameter set, do not have the tagging metadata. The SDK hoists the `x-amz-tagging` header to the query string, which is ignored by S3. S3 requires the `x-amz-tagging` to be a signed header.

**Version of AWS SDK for Go?**
v0.31.0`

**Version of Go (`go version`)?**
v1.15.x

**To Reproduce (observed behavior)**
```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

func main() {
	bucket := os.Args[1]
	key := os.Args[2]
	fileToPut := os.Args[3]

	presigned, err := getPresignedPut(context.TODO(), bucket, key)
	if err != nil {
		log.Fatalf("failed to get presigned URL, %v", err)
	}

	var headerStr strings.Builder
	for k, vs := range presigned.SignedHeader {
		for _, v := range vs {
			fmt.Fprintf(&headerStr, "-H \"%s: %s\" \\\n", k, v)
		}
	}
	fmt.Printf("curl -X %s \\\n%s-d @%s \\\n%q\n",
		presigned.Method, headerStr.String(), fileToPut, presigned.URL)
}

func getPresignedPut(ctx context.Context, bucket, key string) (*v4.PresignedHTTPRequest, error) {
	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load config, %w", err)
	}

	client := s3.NewPresignClient(s3.NewFromConfig(cfg))

	presigned, err := client.PresignPutObject(ctx, &s3.PutObjectInput{
		Bucket:  &bucket,
		Key:     &key,
		Tagging: aws.String("mytagname=mytagvalue"),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get PutObject presigned URL, %w", err)
	}

	return presigned, nil
}
```

**Expected behavior**
To be able to put the object to S3 with the tagged header.

**Additional context**

### PR DESCRIPTION
**Pull request by jasdel**
The `x-amz-tagging` header should not be hoisted to the query string and must be sent as a signed header. If the value is hoisted to the query string in a presigned Put, it is ignored by Amazon S3.

Fixes #1016

### CODE REVIEW

File: aws/signer/internal/v4/headers.go [hunk 1]
```diff
@@ -53,6 +53,7 @@ var RequiredSignedHeaders = Rules{
 			"X-Amz-Storage-Class":                                         struct{}{},
 			"X-Amz-Website-Redirect-Location":                             struct{}{},
 			"X-Amz-Content-Sha256":                                        struct{}{},
+			"X-Amz-Tagging":                                               struct{}{},
```
Comment (skotambkar) [inline aws/signer/internal/v4/headers.go:56]: 1. Is this a valid change for any other rest based service apart from `s3` which use this Header?

**Review by skotambkar — APPROVED** [review]

**Review by skmcgrail — APPROVED** [review]

File: aws/signer/internal/v4/headers.go (hunk 1 above)
Comment (jasdel) [reply aws/signer/internal/v4/headers.go:56]: Yeah this would be valid for all other services, as not hoisting headers is valid approach. In addition S3 is the only service that sends this header for a presigned url.
