### PR TITLE
Fix flex checksum nil dereference issue

### LINKED ISSUE #2963: Panic in `s3.PutBucketOwnershipControls` with `Release 2025-01-15` updates
### Acknowledgements

- [x] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [x] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

We are getting a panic in the `s3.PutBucketOwnershipControls` with the `Release 2025-01-15` CRC updates:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1051a08c0]

goroutine 6034 [running]:
github.com/aws/aws-sdk-go-v2/service/internal/checksum.(*setupInputContext).HandleInitialize(0x140041b28e8, {0x11ea79290, 0x14016806030}, {{0x11d4b5220?, 0x140167a9b90?}}, {0x11e7a8840, 0x1400af84aa0})
	/Users/kewbank/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.5.0/middleware_setup_context.go:49 +0x40
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	/Users/kewbank/go/pkg/mod/github.com/aws/smithy-go@v1.22.1/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/service/s3.(*spanInitializeStart).HandleInitialize(0x0?, {0x11ea79290?, 0x14016806030?}, {{0x11d4b5220?, 0x140167a9b90?}}, {0x11e7a8840, 0x1400af84ac0})
	/Users/kewbank/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.73.0/api_client.go:1233 +0x7c
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	/Users/kewbank/go/pkg/mod/github.com/aws/smithy-go@v1.22.1/middleware/step_initialize.go:200
github.com/aws/smithy-go/middleware.(*InitializeStep).HandleMiddleware(0x0?, {0x11ea79290, 0x14016806030}, {0x11d4b5220, 0x140167a9b90}, {0x11e7a54c0, 0x1400af849a0})
	/Users/kewbank/go/pkg/mod/github.com/aws/smithy-go@v1.22.1/middleware/step_initialize.go:114 +0x1ec
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/Users/kewbank/go/pkg/mod/github.com/aws/smithy-go@v1.22.1/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.(*Stack).HandleMiddleware(0x0?, {0x11ea79290, 0x14016806030}, {0x11d4b5220, 0x140167a9b90}, {0x11e7a5460?, 0x1400af84900?})
	/Users/kewbank/go/pkg/mod/github.com/aws/smithy-go@v1.22.1/middleware/stack.go:109 +0x12c
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/Users/kewbank/go/pkg/mod/github.com/aws/smithy-go@v1.22.1/middleware/middleware.go:57
github.com/aws/aws-sdk-go-v2/service/s3.(*Client).invokeOperation(0x1401317c400, {0x11ea79290?, 0x140167a9920?}, {0x1191a6532, 0x1a}, {0x11d4b5220, 0x140167a9b90}, {0x0, 0x0, 0x1400af84800?}, ...)
	/Users/kewbank/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.73.0/api_client.go:301 +0x900
github.com/aws/aws-sdk-go-v2/service/s3.(*Client).PutBucketOwnershipControls(0x0?, {0x11ea79290?, 0x140167a9920?}, 0x10?, {0x0?, 0x2c?, 0x156877bd0?})
	/Users/kewbank/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.73.0/api_op_PutBucketOwnershipControls.go:39 +0xbc
github.com/hashicorp/terraform-provider-aws/internal/service/s3.resourceBucketOwnershipControlsCreate({0x11ea79290, 0x140167a9920}, 0x140257eaf00, {0x11e72a440, 0x14021410500})
	/Users/kewbank/altsrc.2/github.com/hashicorp/terraform-provider-aws/internal/service/s3/bucket_ownership_controls.go:79 +0x210
```

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Expected Behavior

No panics.

### Current Behavior

See above.

### Reproduction Steps

TBD

### Possible Solution

_No response_

### Additional Information/Context

https://github.com/hashicorp/terraform-provider-aws/pull/40963

### AWS Go SDK V2 Module Versions Used

```console
% grep github.com/aws go.mod
	github.com/aws/aws-sdk-go v1.55.6
	github.com/aws/aws-sdk-go-v2 v1.33.0
	github.com/aws/aws-sdk-go-v2/config v1.29.0
	github.com/aws/aws-sdk-go-v2/credentials v1.17.53
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.16.24
	github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.17.50
	github.com/aws/aws-sdk-go-v2/service/accessanalyzer v1.36.7
	github.com/aws/aws-sdk-go-v2/service/account v1.22.3
	github.com/aws/aws-sdk-go-v2/service/acm v1.30.12
	github.com/aws/aws-sdk-go-v2/service/acmpca v1.37.12
	github.com/aws/aws-sdk-go-v2/service/amp v1.30.8
	github.com/aws/aws-sdk-go-v2/service/amplify v1.28.3
	github.com/aws/aws-sdk-go-v2/service/apigateway v1.28.6
	github.com/aws/aws-sdk-go-v2/service/apigatewayv2 v1.24.12
	github.com/aws/aws-sdk-go-v2/service/appconfig v1.36.6
	github.com/aws/aws-sdk-go-v2/service/appfabric v1.11.10
	github.com/aws/aws-sdk-go-v2/service/appflow v1.45.11
	github.com/aws/aws-sdk-go-v2/service/appintegrations v1.30.10
	github.com/aws/aws-sdk-go-v2/service/applicationautoscaling v1.34.7
	github.com/aws/aws-sdk-go-v2/service/applicationinsights v1.29.8
	github.com/aws/aws-sdk-go-v2/service/applicationsignals v1.7.5
	github.com/aws/aws-sdk-go-v2/service/appmesh v1.29.10
	github.com/aws/aws-sdk-go-v2/service/apprunner v1.32.10
	github.com/aws/aws-sdk-go-v2/service/appstream v1.42.3
	github.com/aws/aws-sdk-go-v2/service/appsync v1.41.2
	github.com/aws/aws-sdk-go-v2/service/athena v1.49.4
	github.com/aws/aws-sdk-go-v2/service/auditmanager v1.37.10
	github.com/aws/aws-sdk-go-v2/service/autoscaling v1.51.6
	github.com/aws/aws-sdk-go-v2/service/autoscalingplans v1.24.10
	github.com/aws/aws-sdk-go-v2/service/backup v1.40.3
	github.com/aws/aws-sdk-go-v2/service/batch v1.49.5
	github.com/aws/aws-sdk-go-v2/service/bcmdataexports v1.7.10
	github.com/aws/aws-sdk-go-v2/service/bedrock v1.26.1
	github.com/aws/aws-sdk-go-v2/service/bedrockagent v1.33.2
	github.com/aws/aws-sdk-go-v2/service/budgets v1.29.4
	github.com/aws/aws-sdk-go-v2/service/chatbot v1.9.4
	github.com/aws/aws-sdk-go-v2/service/chime v1.34.10
	github.com/aws/aws-sdk-go-v2/service/chimesdkmediapipelines v1.21.5
	github.com/aws/aws-sdk-go-v2/service/chimesdkvoice v1.20.3
	github.com/aws/aws-sdk-go-v2/service/cleanrooms v1.21.3
	github.com/aws/aws-sdk-go-v2/service/cloud9 v1.28.11
	github.com/aws/aws-sdk-go-v2/service/cloudcontrol v1.23.6
	github.com/aws/aws-sdk-go-v2/service/cloudformation v1.56.6
	github.com/aws/aws-sdk-go-v2/service/cloudfront v1.44.4
	github.com/aws/aws-sdk-go-v2/service/cloudfrontkeyvaluestore v1.8.10
	github.com/aws/aws-sdk-go-v2/service/cloudhsmv2 v1.29.2
	github.com/aws/aws-sdk-go-v2/service/cloudsearch v1.26.9
	github.com/aws/aws-sdk-go-v2/service/cloudtrail v1.46.8
	github.com/aws/aws-sdk-go-v2/service/cloudwatch v1.43.8
	github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs v1.45.5
	github.com/aws/aws-sdk-go-v2/service/codeartifact v1.33.10
	github.com/aws/aws-sdk-go-v2/service/codebuild v1.50.1
	github.com/aws/aws-sdk-go-v2/service/codecatalyst v1.17.10
	github.com/aws/aws-sdk-go-v2/service/codecommit v1.27.10
	github.com/aws/aws-sdk-go-v2/service/codeconnections v1.5.10
	github.com/aws/aws-sdk-go-v2/service/codedeploy v1.29.12
	github.com/aws/aws-sdk-go-v2/service/codeguruprofiler v1.24.10
	github.com/aws/aws-sdk-go-v2/service/codegurureviewer v1.29.11
	github.com/aws/aws-sdk-go-v2/service/codepipeline v1.38.3
	github.com/aws/aws-sdk-go-v2/service/codestarconnections v1.29.10
	github.com/aws/aws-sdk-go-v2/service/codestarnotifications v1.26.10
	github.com/aws/aws-sdk-go-v2/service/cognitoidentity v1.28.0
	github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider v1.48.5
	github.com/aws/aws-sdk-go-v2/service/comprehend v1.35.11
	github.com/aws/aws-sdk-go-v2/service/computeoptimizer v1.41.1
	github.com/aws/aws-sdk-go-v2/service/configservice v1.51.6
	github.com/aws/aws-sdk-go-v2/service/connect v1.123.3
	github.com/aws/aws-sdk-go-v2/service/connectcases v1.21.10
	github.com/aws/aws-sdk-go-v2/service/controltower v1.20.4
	github.com/aws/aws-sdk-go-v2/service/costandusagereportservice v1.28.10
	github.com/aws/aws-sdk-go-v2/service/costexplorer v1.46.2
	github.com/aws/aws-sdk-go-v2/service/costoptimizationhub v1.11.4
	github.com/aws/aws-sdk-go-v2/service/customerprofiles v1.44.3
	github.com/aws/aws-sdk-go-v2/service/databasemigrationservice v1.45.5
	github.com/aws/aws-sdk-go-v2/service/databrew v1.33.10
	github.com/aws/aws-sdk-go-v2/service/dataexchange v1.33.8
	github.com/aws/aws-sdk-go-v2/service/datapipeline v1.25.10
	github.com/aws/aws-sdk-go-v2/service/datasync v1.44.5
	github.com/aws/aws-sdk-go-v2/service/datazone v1.25.4
	github.com/aws/aws-sdk-go-v2/service/dax v1.23.10
	github.com/aws/aws-sdk-go-v2/service/detective v1.31.10
	github.com/aws/aws-sdk-go-v2/service/devicefarm v1.28.10
	github.com/aws/aws-sdk-go-v2/service/devopsguru v1.34.10
	github.com/aws/aws-sdk-go-v2/service/directconnect v1.30.6
	github.com/aws/aws-sdk-go-v2/service/directoryservice v1.30.11
	github.com/aws/aws-sdk-go-v2/service/dlm v1.29.5
	github.com/aws/aws-sdk-go-v2/service/docdb v1.40.4
	github.com/aws/aws-sdk-go-v2/service/docdbelastic v1.14.7
	github.com/aws/aws-sdk-go-v2/service/drs v1.30.10
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.39.4
	github.com/aws/aws-sdk-go-v2/service/ec2 v1.199.2
	github.com/aws/aws-sdk-go-v2/service/ecr v1.38.5
	github.com/aws/aws-sdk-go-v2/service/ecrpublic v1.29.3
	github.com/aws/aws-sdk-go-v2/service/ecs v1.53.6
	github.com/aws/aws-sdk-go-v2/service/efs v1.34.4
	github.com/aws/aws-sdk-go-v2/service/eks v1.56.4
	github.com/aws/aws-sdk-go-v2/service/elasticache v1.44.6
	github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk v1.28.11
	github.com/aws/aws-sdk-go-v2/service/elasticloadbalancing v1.28.11
	github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2 v1.43.6
	github.com/aws/aws-sdk-go-v2/service/elasticsearchservice v1.32.12
	github.com/aws/aws-sdk-go-v2/service/elastictranscoder v1.27.11
	github.com/aws/aws-sdk-go-v2/service/emr v1.47.6
	github.com/aws/aws-sdk-go-v2/service/emrcontainers v1.33.11
	github.com/aws/aws-sdk-go-v2/service/emrserverless v1.27.3
	github.com/aws/aws-sdk-go-v2/service/eventbridge v1.36.5
	github.com/aws/aws-sdk-go-v2/service/evidently v1.23.10
	github.com/aws/aws-sdk-go-v2/service/finspace v1.28.10
	github.com/aws/aws-sdk-go-v2/service/firehose v1.35.5
	github.com/aws/aws-sdk-go-v2/service/fis v1.31.5
	github.com/aws/aws-sdk-go-v2/service/fms v1.39.1
	github.com/aws/aws-sdk-go-v2/service/fsx v1.51.4
	github.com/aws/aws-sdk-go-v2/service/gamelift v1.39.1
	github.com/aws/aws-sdk-go-v2/service/glacier v1.26.11
	github.com/aws/aws-sdk-go-v2/service/globalaccelerator v1.29.10
	github.com/aws/aws-sdk-go-v2/service/glue v1.105.2
	github.com/aws/aws-sdk-go-v2/service/grafana v1.26.10
	github.com/aws/aws-sdk-go-v2/service/greengrass v1.27.10
	github.com/aws/aws-sdk-go-v2/service/groundstation v1.31.11
	github.com/aws/aws-sdk-go-v2/service/guardduty v1.52.4
	github.com/aws/aws-sdk-go-v2/service/healthlake v1.28.10
	github.com/aws/aws-sdk-go-v2/service/iam v1.38.6
	github.com/aws/aws-sdk-go-v2/service/identitystore v1.27.11
	github.com/aws/aws-sdk-go-v2/service/imagebuilder v1.40.2
	github.com/aws/aws-sdk-go-v2/service/inspector v1.25.10
	github.com/aws/aws-sdk-go-v2/service/inspector2 v1.34.4
	github.com/aws/aws-sdk-go-v2/service/internetmonitor v1.20.8
	github.com/aws/aws-sdk-go-v2/service/invoicing v1.0.3
	github.com/aws/aws-sdk-go-v2/service/iot v1.62.3
	github.com/aws/aws-sdk-go-v2/service/iotanalytics v1.26.10
	github.com/aws/aws-sdk-go-v2/service/iotevents v1.27.10
	github.com/aws/aws-sdk-go-v2/service/ivs v1.42.5
	github.com/aws/aws-sdk-go-v2/service/ivschat v1.16.10
	github.com/aws/aws-sdk-go-v2/service/kafka v1.38.11
	github.com/aws/aws-sdk-go-v2/service/kafkaconnect v1.22.1
	github.com/aws/aws-sdk-go-v2/service/kendra v1.55.3
	github.com/aws/aws-sdk-go-v2/service/keyspaces v1.16.5
	github.com/aws/aws-sdk-go-v2/service/kinesis v1.32.12
	github.com/aws/aws-sdk-go-v2/service/kinesisanalytics v1.25.11
	github.com/aws/aws-sdk-go-v2/service/kinesisanalyticsv2 v1.31.11
	github.com/aws/aws-sdk-go-v2/service/kinesisvideo v1.27.10
	github.com/aws/aws-sdk-go-v2/service/kms v1.37.12
	github.com/aws/aws-sdk-go-v2/service/lakeformation v1.39.4
	github.com/aws/aws-sdk-go-v2/service/lambda v1.69.6
	github.com/aws/aws-sdk-go-v2/service/launchwizard v1.8.10
	github.com/aws/aws-sdk-go-v2/service/lexmodelbuildingservice v1.28.10
	github.com/aws/aws-sdk-go-v2/service/lexmodelsv2 v1.49.11
	github.com/aws/aws-sdk-go-v2/service/licensemanager v1.29.11
	github.com/aws/aws-sdk-go-v2/service/lightsail v1.42.10
	github.com/aws/aws-sdk-go-v2/service/location v1.42.11
	github.com/aws/aws-sdk-go-v2/service/lookoutmetrics v1.31.10
	github.com/aws/aws-sdk-go-v2/service/m2 v1.19.3
	github.com/aws/aws-sdk-go-v2/service/macie2 v1.44.4
	github.com/aws/aws-sdk-go-v2/service/mediaconnect v1.37.3
	github.com/aws/aws-sdk-go-v2/service/mediaconvert v1.65.2
	github.com/aws/aws-sdk-go-v2/service/medialive v1.65.3
	github.com/aws/aws-sdk-go-v2/service/mediapackage v1.34.10
	github.com/aws/aws-sdk-go-v2/service/mediapackagev2 v1.20.5
	github.com/aws/aws-sdk-go-v2/service/mediastore v1.24.10
	github.com/aws/aws-sdk-go-v2/service/memorydb v1.25.3
	github.com/aws/aws-sdk-go-v2/service/mgn v1.32.10
	github.com/aws/aws-sdk-go-v2/service/mq v1.27.11
	github.com/aws/aws-sdk-go-v2/service/mwaa v1.33.5
	github.com/aws/aws-sdk-go-v2/service/neptune v1.35.11
	github.com/aws/aws-sdk-go-v2/service/neptunegraph v1.15.5
	github.com/aws/aws-sdk-go-v2/service/networkfirewall v1.44.9
	github.com/aws/aws-sdk-go-v2/service/networkmanager v1.32.5
	github.com/aws/aws-sdk-go-v2/service/networkmonitor v1.7.10
	github.com/aws/aws-sdk-go-v2/service/oam v1.15.12
	github.com/aws/aws-sdk-go-v2/service/opensearch v1.45.5
	github.com/aws/aws-sdk-go-v2/service/opensearchserverless v1.17.8
	github.com/aws/aws-sdk-go-v2/service/opsworks v1.26.11
	github.com/aws/aws-sdk-go-v2/service/organizations v1.37.2
	github.com/aws/aws-sdk-go-v2/service/osis v1.14.10
	github.com/aws/aws-sdk-go-v2/service/outposts v1.48.2
	github.com/aws/aws-sdk-go-v2/service/paymentcryptography v1.16.5
	github.com/aws/aws-sdk-go-v2/service/pcaconnectorad v1.9.10
	github.com/aws/aws-sdk-go-v2/service/pcs v1.2.11
	github.com/aws/aws-sdk-go-v2/service/pinpoint v1.34.10
	github.com/aws/aws-sdk-go-v2/service/pinpointsmsvoicev2 v1.18.5
	github.com/aws/aws-sdk-go-v2/service/pipes v1.18.8
	github.com/aws/aws-sdk-go-v2/service/polly v1.45.11
	github.com/aws/aws-sdk-go-v2/service/pricing v1.32.10
	github.com/aws/aws-sdk-go-v2/service/qbusiness v1.19.5
	github.com/aws/aws-sdk-go-v2/service/qldb v1.25.10
	github.com/aws/aws-sdk-go-v2/service/quicksight v1.82.3
	github.com/aws/aws-sdk-go-v2/service/ram v1.29.12
	github.com/aws/aws-sdk-go-v2/service/rbin v1.21.7
	github.com/aws/aws-sdk-go-v2/service/rds v1.93.6
	github.com/aws/aws-sdk-go-v2/service/redshift v1.53.6
	github.com/aws/aws-sdk-go-v2/service/redshiftdata v1.31.7
	github.com/aws/aws-sdk-go-v2/service/redshiftserverless v1.25.3
	github.com/aws/aws-sdk-go-v2/service/rekognition v1.45.12
	github.com/aws/aws-sdk-go-v2/service/resiliencehub v1.29.3
	github.com/aws/aws-sdk-go-v2/service/resourceexplorer2 v1.16.5
	github.com/aws/aws-sdk-go-v2/service/resourcegroups v1.27.12
	github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi v1.25.12
	github.com/aws/aws-sdk-go-v2/service/rolesanywhere v1.16.10
	github.com/aws/aws-sdk-go-v2/service/route53 v1.48.1
	github.com/aws/aws-sdk-go-v2/service/route53domains v1.28.4
	github.com/aws/aws-sdk-go-v2/service/route53profiles v1.4.10
	github.com/aws/aws-sdk-go-v2/service/route53recoverycontrolconfig v1.25.11
	github.com/aws/aws-sdk-go-v2/service/route53recoveryreadiness v1.21.10
	github.com/aws/aws-sdk-go-v2/service/route53resolver v1.34.7
	github.com/aws/aws-sdk-go-v2/service/rum v1.21.10
	github.com/aws/aws-sdk-go-v2/service/s3 v1.73.0
	github.com/aws/aws-sdk-go-v2/service/s3control v1.52.5
	github.com/aws/aws-sdk-go-v2/service/s3outposts v1.28.10
	github.com/aws/aws-sdk-go-v2/service/s3tables v1.0.3
	github.com/aws/aws-sdk-go-v2/service/sagemaker v1.172.3
	github.com/aws/aws-sdk-go-v2/service/scheduler v1.12.11
	github.com/aws/aws-sdk-go-v2/service/schemas v1.28.12
	github.com/aws/aws-sdk-go-v2/service/secretsmanager v1.34.12
	github.com/aws/aws-sdk-go-v2/service/securityhub v1.55.4
	github.com/aws/aws-sdk-go-v2/service/securitylake v1.19.9
	github.com/aws/aws-sdk-go-v2/service/serverlessapplicationrepository v1.24.10
	github.com/aws/aws-sdk-go-v2/service/servicecatalog v1.32.10
	github.com/aws/aws-sdk-go-v2/service/servicecatalogappregistry v1.30.10
	github.com/aws/aws-sdk-go-v2/service/servicediscovery v1.34.5
	github.com/aws/aws-sdk-go-v2/service/servicequotas v1.25.12
	github.com/aws/aws-sdk-go-v2/service/ses v1.29.5
	github.com/aws/aws-sdk-go-v2/service/sesv2 v1.41.0
	github.com/aws/aws-sdk-go-v2/service/sfn v1.34.6
	github.com/aws/aws-sdk-go-v2/service/shield v1.29.10
	github.com/aws/aws-sdk-go-v2/service/signer v1.26.11
	github.com/aws/aws-sdk-go-v2/service/sns v1.33.12
	github.com/aws/aws-sdk-go-v2/service/sqs v1.37.8
	github.com/aws/aws-sdk-go-v2/service/ssm v1.56.6
	github.com/aws/aws-sdk-go-v2/service/ssmcontacts v1.26.10
	github.com/aws/aws-sdk-go-v2/service/ssmincidents v1.34.11
	github.com/aws/aws-sdk-go-v2/service/ssmquicksetup v1.3.4
	github.com/aws/aws-sdk-go-v2/service/ssmsap v1.19.3
	github.com/aws/aws-sdk-go-v2/service/sso v1.24.10
	github.com/aws/aws-sdk-go-v2/service/ssoadmin v1.29.10
	github.com/aws/aws-sdk-go-v2/service/storagegateway v1.34.10
	github.com/aws/aws-sdk-go-v2/service/sts v1.33.8
	github.com/aws/aws-sdk-go-v2/service/swf v1.27.13
	github.com/aws/aws-sdk-go-v2/service/synthetics v1.31.5
	github.com/aws/aws-sdk-go-v2/service/taxsettings v1.7.4
	github.com/aws/aws-sdk-go-v2/service/timestreaminfluxdb v1.7.3
	github.com/aws/aws-sdk-go-v2/service/timestreamquery v1.29.4
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite v1.29.11
	github.com/aws/aws-sdk-go-v2/service/transcribe v1.42.1
	github.com/aws/aws-sdk-go-v2/service/transfer v1.55.4
	github.com/aws/aws-sdk-go-v2/service/verifiedpermissions v1.20.6
	github.com/aws/aws-sdk-go-v2/service/vpclattice v1.13.5
	github.com/aws/aws-sdk-go-v2/service/waf v1.25.10
	github.com/aws/aws-sdk-go-v2/service/wafregional v1.25.10
	github.com/aws/aws-sdk-go-v2/service/wafv2 v1.55.9
	github.com/aws/aws-sdk-go-v2/service/wellarchitected v1.34.10
	github.com/aws/aws-sdk-go-v2/service/worklink v1.23.2
	github.com/aws/aws-sdk-go-v2/service/workspaces v1.52.0
	github.com/aws/aws-sdk-go-v2/service/workspacesweb v1.25.4
	github.com/aws/aws-sdk-go-v2/service/xray v1.30.6
	github.com/aws/smithy-go v1.22.1
	github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.6.7 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.3.28 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.6.28 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.8.1 // indirect
	github.com/aws/aws-sdk-go-v2/internal/v4a v1.3.28 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.12.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.5.0 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.10.9 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.12.9 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.18.9 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.28.9 // indirect
	go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws v0.58.0 // indirect
```

### Compiler and Version used

go version go1.23.3 darwin/arm64

### Operating System and version

macos

### PR DESCRIPTION
**Pull request by wty-Bryant**
The latest flexible checksum feature will nil deference and panic operations(e.g. `s3.PutBucketOwnershipControls`) that require checksum but don't have input algorithm setting, this pr fixes that via nil checking before getting checksum algorithm

It has been tested locally that operation mentioned above will not panic after this change and will use crc32 checksum by default 

close #2963 by merging this pr

### CODE REVIEW

File: service/internal/checksum/middleware_setup_context.go [hunk 1]
```diff
@@ -46,9 +46,11 @@ func (m *setupInputContext) HandleInitialize(
 ) (
 	out middleware.InitializeOutput, metadata middleware.Metadata, err error,
 ) {
-	if algorithm, ok := m.GetAlgorithm(in.Parameters); ok {
-		ctx = internalcontext.SetChecksumInputAlgorithm(ctx, algorithm)
-		return next.HandleInitialize(ctx, in)
+	if m.GetAlgorithm != nil {
```
Comment (lucix-aws) [inline service/internal/checksum/middleware_setup_context.go:49]: Can we annotate _why_ this is necessary? It's for operations that require a checksum, but don't have an algorithm setting (meaning we should just be using crc32) correct?

**Review by lucix-aws — COMMENTED** [review]
The PR needs a description/explanation of the change here.

**Comment by lucix-aws** [comment]
Did you verify that
1. operation no longer panics
2. operation ultimately uses crc32?

**Comment by Madrigal** [comment]
Fixes #2963

File: .changelog/2e03eae07dff4beb94963939b6549426.json [hunk 2]
```diff
@@ -0,0 +1,8 @@
+{
+    "id": "2e03eae0-7dff-4beb-9496-3939b6549426",
+    "type": "bugfix",
+    "description": "Fix nil dereference panic for operations that require checksums, but do not have an input setting for which algorithm to use.",
+    "modules": [
+        "service/internal/checksum"
```
Comment (Madrigal) [inline .changelog/2e03eae07dff4beb94963939b6549426.json:6]: should we add service/s3 here?

**Review by Madrigal — APPROVED** [review]

File: .changelog/2e03eae07dff4beb94963939b6549426.json (hunk 2 above)
Comment (lucix-aws) [reply .changelog/2e03eae07dff4beb94963939b6549426.json:6]: It doesn't actually affect service/s3 code, so I'm not sure. I'd rather not in the context of this emergency patch in case it causes some sort of release tooling issue.

Comment (wty-Bryant) [reply .changelog/2e03eae07dff4beb94963939b6549426.json:6]: nope, the fix don't include s3 itself

**Review by lucix-aws — APPROVED** [review]

File: .changelog/2e03eae07dff4beb94963939b6549426.json (hunk 2 above)
Comment (Madrigal) [reply .changelog/2e03eae07dff4beb94963939b6549426.json:6]: OK I'm down to not have it. 

For context, what I was thinking was "where would someone think of looking to see we pushed a fix?"
