### PR TITLE
aws/endpoints: Fix SDK endpoint signing name resolution

### LINKED ISSUE #153: Ensure endpoint resolution falls back to C2J modeled SigningName
The SDK needs to ensure that the C2J modeled SigningName is used if the modeled endpoint does not contain the SigningName field.

Related to aws/aws-sdk-go#1854

### LINKED ISSUE #163: InvalidSignatureException: Credential should be scoped to correct service: 'application-autoscaling'.
Please fill out the sections below to help us address your issue.

2.0.0-preview.3

### Version of Go (`go version`)?

go version go1.10 darwin/amd64

### What issue did you see?

InvalidSignatureException: Credential should be scoped to correct service: 'application-autoscaling'. 

### Steps to reproduce

If you have have an runnable example, please include it.

```go
	cfg, err := external.LoadDefaultAWSConfig()
	if err != nil {
		panic(err)
	}
	cfg.Region = endpoints.UsWest2RegionID

	scale := applicationautoscaling.New(cfg)
	req := scale.RegisterScalableTargetRequest(&applicationautoscaling.RegisterScalableTargetInput{
		MaxCapacity:       aws.Int64(200),
		MinCapacity:       aws.Int64(90),
		ResourceId:        aws.String("service/foo/bar"),
		ScalableDimension: applicationautoscaling.ScalableDimensionEcsServiceDesiredCount,
		ServiceNamespace:  applicationautoscaling.ServiceNamespaceEcs,
	})
	_, err = req.Send()
	if err != nil {
		panic(err)
	}
```

### PR DESCRIPTION
**Pull request by jasdel**
Fixes how the SDK derives service signing names. If the signing name is
not modeled in the endpoints package the service will fallback to the
signing name modeled in the service model.

Fix #163
Fix #153
V2 Port of aws/aws-sdk-go#1854

### CODE REVIEW

File: aws/request.go [hunk 1]
```diff
@@ -103,7 +103,7 @@ func New(cfg Config, metadata Metadata, handlers Handlers,
 	if err == nil {
 		// TODO so ugly
 		metadata.Endpoint = endpoint.URL
-		if len(endpoint.SigningName) > 0 {
+		if len(endpoint.SigningName) > 0 && !endpoint.SigningNameDerived {
```
Comment (xibz) [inline aws/request.go]: Can we just have the endpoint have a get signing name method that returns the correct signing name? I think that'll at least make it cleaner when dealing with cases where it isn't derived.

Comment (jasdel) [reply aws/request.go]: because the signing name are modeled in both endpoint and service models, the SDK has to rely on both sources. In some cases the signing name is not included in the endpoint model,which is the default source.
